### ISSUE TITLE
考虑支持APNS和Huawei Push么

### ISSUE THREAD

**Issue by liuhao86** [joyrun/MixPush#4]
目前国内有远程推送的, 除了魅族和小米外, 还有华为呢, 而苹果远程推送也是比较容易接入, 这一块目前是使用个推做的么?

**Comment by taoweiji** [comment]
华为推送之前其实有考虑接入的，经过测试发现，华为推送不稳定，就算是华为的手机也无法正常收到推送，丢失严重，询问华为推送的工程师，其建议不要使用华为推送，等新版本再用，但是已经过去半年还是没有新版推送。而且也不支持别名绑定。

**Comment by taoweiji** [comment]
目前我公司的苹果的推送是自己实现，成本相对会高些。雏型app可以考虑使用小米，个推来实现，ios的推送本身就支持离线推送，不像android需要考虑那么多。
